// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb5FNILo68mISMPjePwYIFqqaNXX2ht2U',
    appId: '1:960285388676:web:3dbbdbd534387664bf77d1',
    messagingSenderId: '960285388676',
    projectId: 'wishy-back',
    authDomain: 'wishy-back.firebaseapp.com',
    storageBucket: 'wishy-back.firebasestorage.app',
    measurementId: 'G-EDCZVGZ8MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAKQiatwXn4Ya95uWfIyg_JP5906cIc7Q',
    appId: '1:960285388676:android:23d33764101feb1dbf77d1',
    messagingSenderId: '960285388676',
    projectId: 'wishy-back',
    storageBucket: 'wishy-back.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5AAaq1rQt3txXN5xm9wRUpdjbgiv6XJY',
    appId: '1:960285388676:ios:6743a9b1f6602287bf77d1',
    messagingSenderId: '960285388676',
    projectId: 'wishy-back',
    storageBucket: 'wishy-back.firebasestorage.app',
    iosBundleId: 'com.wishy.wishy',
  );
}
