// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Px_5dyq14hSveV5DmzEl5TUx1hVN-Lw',
    appId: '1:1083554086475:web:d5208d61edc24e0fd9d7ce',
    messagingSenderId: '1083554086475',
    projectId: 'luia-48689',
    authDomain: 'luia-48689.firebaseapp.com',
    storageBucket: 'luia-48689.firebasestorage.app',
    measurementId: 'G-PXR0W8LBL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8C6mEUXUTK8OGZPQmDPSfLL3kuHIZQk',
    appId: '1:1083554086475:android:e57640e6e39ab69fd9d7ce',
    messagingSenderId: '1083554086475',
    projectId: 'luia-48689',
    storageBucket: 'luia-48689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlp0APfSZK3QId8CUpZ-hNNEbc6GzKbd8',
    appId: '1:1083554086475:ios:577e54510e129966d9d7ce',
    messagingSenderId: '1083554086475',
    projectId: 'luia-48689',
    storageBucket: 'luia-48689.firebasestorage.app',
    iosBundleId: 'com.example.luia',
  );
}
